name: "Build"
on: pull_request
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  tests:
    runs-on:
      group: aws-highmemory-32-plus-nix
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
        with:
          extra-conf: |
            max-jobs = 4
            cores = 12
            sandbox-fallback = false
      - name: Nix info
        run: nix-shell -p nix-info --run "nix-info -m"
      - uses: cachix/cachix-action@v16
        with:
          name: huggingface
        #    authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
        env:
          USER: github_runner
      - name: Check formatting
        run: nix fmt -- --ci
      - name: Build
        run: nix build -L .#all
